export const CREATE_TEXT_EDITOR_REQUEST = "CREATE_TEXT_EDITOR_REQUEST";
export const CREATE_TEXT_EDITOR_SUCCESS = "CREATE_TEXT_EDITOR_SUCCESS";
export const CREATE_TEXT_EDITOR_FAILURE = "CREATE_TEXT_EDITOR_FAILURE";
