export const CREATE_TEXT_EDITOR_REQUEST = "CREATE_TEXT_EDITOR_REQUEST";
export const CREATE_TEXT_EDITOR_SUCCESS = "CREATE_TEXT_EDITOR_SUCCESS";
export const CREATE_TEXT_EDITOR_FAILURE = "CREATE_TEXT_EDITOR_FAILURE";

export const GET_TEXT_EDITOR_REQUEST = "GET_TEXT_EDITOR_REQUEST";
export const GET_TEXT_EDITOR_SUCCESS = "GET_TEXT_EDITOR_SUCCESS";
export const GET_TEXT_EDITOR_FAILURE = "GET_TEXT_EDITOR_FAILURE";

export const DELETE_TEXT_EDITOR_SUCCESS = "DELETE_TEXT_EDITOR_SUCCESS";

export const EDIT_TEXT_EDITOR_REQUEST = "EDIT_TEXT_EDITOR_REQUEST";
export const EDIT_TEXT_EDITOR_SUCCESS = "EDIT_TEXT_EDITOR_SUCCESS";
export const EDIT_TEXT_EDITOR_FAILURE = "EDIT_TEXT_EDITOR_FAILURE";