export const CREATE_MARKDOWN_EDITOR_REQUEST = "CREATE_MARKDOWN_EDITOR_REQUEST";
export const CREATE_MARKDOWN_EDITOR_SUCCESS = "CREATE_MARKDOWN_EDITOR_SUCCESS";
export const CREATE_MARKDOWN_EDITOR_FAILURE = "CREATE_MARKDOWN_EDITOR_FAILURE";

export const GET_MARKDOWN_EDITOR_REQUEST = "GET_MARKDOWN_EDITOR_REQUEST";
export const GET_MARKDOWN_EDITOR_SUCCESS = "GET_MARKDOWN_EDITOR_SUCCESS";
export const GET_MARKDOWN_EDITOR_FAILURE = "GET_MARKDOWN_EDITOR_FAILURE";

export const DELETE_MARKDOWN_EDITOR_SUCCESS = "DELETE_MARKDOWN_EDITOR_SUCCESS";

export const EDIT_MARKDOWN_EDITOR_REQUEST = "EDIT_MARKDOWN_EDITOR_REQUEST";
export const EDIT_MARKDOWN_EDITOR_SUCCESS = "EDIT_MARKDOWN_EDITOR_SUCCESS";
export const EDIT_MARKDOWN_EDITOR_FAILURE = "EDIT_MARKDOWN_EDITOR_FAILURE";